#*****************************#
#*** BII-LRPC constuction X(b=2) configuration ***#
#*****************************#

lowercase_scheme_name: biix
uppercase_scheme_name: BIIX
source_files: [kem.c, kem.h, parsing.c, parsing.h, types.h]
lrpc: True
