#*****************************#
#*** ROLLO-I configuration ***#
#*****************************#

lowercase_scheme_name: rolloI
uppercase_scheme_name: ROLLOI
source_files: [kem.c, kem.h, parsing.c, parsing.h, types.h]
lrpc: True